version: "3"
services:
  #PHP Service
  app:
    depends_on:
      - db
      - redis
    image: lakhveerbawa/phpdock:php841
    command:
      - php-fpm
    expose:
      - 9000
      - 9003
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    labels:
      - "traefik.enable=false"
    volumes:
      - ./:/var/www
      - ./docker/config/php/production.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    #Nginx Service


  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/config/nginx/conf.d.production/:/etc/nginx/conf.d/
    labels:
      - "traefik.enable=true"

      # Main router (non-www)
      - "traefik.http.routers.realtor-clearmesh-ca.rule=Host(`realtor.clearmesh.ca`)"
      - "traefik.http.routers.realtor-clearmesh-ca.entrypoints=websecure"
      - "traefik.http.routers.realtor-clearmesh-ca.tls=true"
      - "traefik.http.routers.realtor-clearmesh-ca.tls.certresolver=letsencrypt"
      - "traefik.http.routers.realtor-clearmesh-ca.service=realtor-clearmesh-ca"
      # Service
      - "traefik.http.services.realtor-clearmesh-ca.loadbalancer.server.port=80"
    networks:
      - app-network
      - web # traefik network
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: lakhbawa
      POSTGRES_PASSWORD: "${DB_PASSWORD:-Sartaj@jaan855}"
      POSTGRES_DB: realtor_saas
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "4332:5432"
    labels:
      - "traefik.enable=false"
    networks: [app-network]


  adminer:
    image: adminer:latest
    ports:
      - "4380:8080"
    depends_on:
      - db
    networks: [app-network]
  redis:
    image: redis:latest
    restart: unless-stopped
    tty: true
    expose:
      - 6379
    volumes:
      - redisdata:/data
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
  web:
    external: true
#Volumes
volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local

#  default:
#    external:
#      name: nginx-proxy
