version: "3"
services:
  #PHP Service
  realtor-app:
    depends_on:
      - realtor-db
    image: lakhveerbawa/phpdock:arm841
    command:
      - php-fpm
    expose:
      - 9000
      - 9003
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - realtor-network
    #Nginx Service

  realtor-job:
    depends_on:
      - realtor-db
    image: lakhveerbawa/phpdock:arm841
    entrypoint: /usr/bin/supervisord -n -c /etc/supervisord.conf
    expose:
      - 9000
      - 13714
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: job
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./docker/config/php/production.ini:/usr/local/etc/php/conf.d/local.ini
      - ./.env:/var/www/.env
      - ./:/var/www
      - ./docker/config/supervisor/queue/conf.d.queue:/etc/supervisor/conf.d
      - ./docker/worker/supervisord.conf:/etc/supervisord.conf:delegated
    networks:
      - realtor-network
  #Nginx Service
  realtor-nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "4300:80"
      - "4301:443"
    volumes:
      - ./:/var/www
      - ./docker/config/nginx/conf.d.local/:/etc/nginx/conf.d/
    networks:
      - realtor-network
  realtor-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: realtor
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "4332:5432"
    networks: [realtor-network]

  realtor-adminer:
    image: adminer:latest
    ports:
      - "4380:8080"
    depends_on:
      - realtor-db
    networks: [realtor-network]
  realtor-redis:
    image: arm64v8/redis
    restart: unless-stopped
    tty: true
    expose:
      - 6379
    volumes:
      - redisdata:/data
    networks:
      - realtor-network


#Docker Networks
networks:
  realtor-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
#  default:
#    external:
#      name: nginx-proxy
